# Generated by Django 2.1.5 on 2019-03-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotext', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencepdf',
            old_name='apa_reference',
            new_name='_apa_reference',
        ),
        migrations.RenameField(
            model_name='referenceweb',
            old_name='apa_reference',
            new_name='_apa_reference',
        ),
    ]
