# Generated by Django 2.1.5 on 2019-03-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotext', '0002_auto_20190319_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencepdf',
            name='_content',
        ),
        migrations.RemoveField(
            model_name='referenceweb',
            name='_content',
        ),
    ]
