# Generated by Django 2.1.7 on 2019-04-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotext', '0004_webography_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webography',
            name='name',
        ),
        migrations.AddField(
            model_name='webography',
            name='_name',
            field=models.TextField(default='', null=True),
        ),
    ]
