# Generated by Django 2.1.7 on 2019-04-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotext', '0005_auto_20190401_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webography',
            name='raw_urls',
        ),
    ]
