# Generated by Django 2.1.5 on 2019-03-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotext', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencepdf',
            old_name='content',
            new_name='_content',
        ),
        migrations.RenameField(
            model_name='referenceweb',
            old_name='content',
            new_name='_content',
        ),
    ]
